drop trigger updated_at_attributes_count on attributes_count;
drop trigger updated_at_event_count on events_count;
drop trigger updated_at_attributes on attributes;
drop trigger updated_at_events on events;
drop trigger updated_topics on topics;
drop trigger updated_at_sources on sources;
drop function sync_updated_at;
drop index attributes_count_id_uindex;
drop table attributes_count;
drop index events_count_id_uindex;
drop table events_count;
drop index attributes_id_uindex;
drop table attributes;
drop index event_id_uindex;
drop table events;
drop index topic_id_uindex;
drop table topics;
drop index source_id_uindex;
drop table sources;
